name: Publish to Artifactory

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Semantic Version
        run: ./gradlew printVersion
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PUBLISH_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PUBLISH_AWS_ACCESS_SECRET }}
          aws-region: eu-west-1
      - name: Set codeartifact password
        run: |
          export CODEARTIFACT_PASSWORD=`aws codeartifact get-authorization-token --domain plurex --domain-owner 253115806526 --region eu-west-1 --query authorizationToken --output text`
          echo "CODEARTIFACT_PASSWORD=$CODEARTIFACT_PASSWORD" >> "$GITHUB_ENV"
      - name: Build and Deploy
        run: ./gradlew publish

