name: Release Patch

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/semver-release-action@v2
        with:
          bump: patch
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}

