name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Specify the release version [major, minor, patch]'
        required: true
        default: 'minor' # Default value if no input is provided

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: zwaldowski/semver-release-action@v2
        with:
         bump: ${{ inputs.release_version }}
         prefix: v
         github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Semantic Version
        run: ./gradlew printVersion
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SS_CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SS_CICD_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Build and Deploy
        run: |
          export CODEARTIFACT_PASSWORD=`aws codeartifact get-authorization-token --domain ${{ vars.CODEARTIFACT_DOMAIN }} --domain-owner ${{ vars.CODEARTIFACT_DOMAIN_OWNER }} --region eu-west-1 --query authorizationToken --output text`
          ./gradlew publish
