# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PUBLISH_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PUBLISH_AWS_ACCESS_SECRET }}
          aws-region: eu-west-1
      - name: Run Tests
        run: |
          export CODEARTIFACT_PASSWORD=`aws codeartifact get-authorization-token --domain plurex --domain-owner 253115806526 --region eu-west-1 --query authorizationToken --output text`
          ./gradlew test
